version: "3.5"
services:
  node-red:
    image: matuzalemmuller/tisa:latest
    hostname: node-red
    container_name: node-red
    expose:
      - "1880"
    ports:
      - "80:1880"
    networks:
      default:
        ipv4_address: 172.18.1.2

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      default:
        ipv4_address: 172.18.1.3

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24