version: "3.5"
services:
  node-red:
    image: matuzalemmuller/tisa:node-red-insecure
    hostname: node-red
    container_name: node-red
    restart: always
    expose:
      - "1880"
    ports:
      - "80:1880"
    volumes:
      - ./:/app
    networks:
      default:
        ipv4_address: 172.18.1.2

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      default:
        ipv4_address: 172.18.1.3
    
  flask-server:
    image: matuzalemmuller/tisa:flask-server
    hostname: flask-server
    container_name: flask-server
    restart: always
    expose:
      - "80"
    networks:
      default:
        ipv4_address: 172.18.1.4

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24