version: "3.5"
services:
  node-red:
    build: node-red
    hostname: node-red
    container_name: node-red
    restart: always
    expose:
      - "1880"
    ports:
      - "80:1880"
    volumes:
      - ./:/app
    networks:
      default:
        ipv4_address: 172.18.1.2

  flask-server:
    build: flask
    hostname: flask
    container_name: flask
    restart: always
    environment:
      - APP_EMAIL_ADDRESS=email@example.com
      - APP_PASSWORD=password
    expose:
      - "80"
    networks:
      default:
        ipv4_address: 172.18.1.3

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24